#!/usr/bin/env bash

# Change the command below to use a Python 3 binary that runs in an environment
# with the requirements from requirements.txt installed.

# With virtualenv installed, the following commands will get you there:
#
# $ mkvirtualenv pygmx
# $ pip install -r src/pygmx/requirements.txt
#
# The environment you just created should be at `$HOME/.virtualenvs/pygmx/`, as
# in the command below:

${HOME}/.virtualenvs/pygmx/bin/python3 "$@"
